sudo: required
services:
  - docker

before_install:
  - docker build -t emilerodenbach/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true emilerodenbach/react-test npm run test

after_success:
  - docker build -t emilerodenbach/multi-client ./client
  - docker build -t emilerodenbach/multi-nginx ./nginx
  - docker build -t emilerodenbach/multi-server ./server
  - docker build -t emilerodenbach/multi-worker ./worker
 # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub    
  - docker push emilerodenbach/multi-client
  - docker push emilerodenbach/multi-nginx
  - docker push emilerodenbach/multi-server
  - docker push emilerodenbach/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  # http://dockerreact-env.wz5y3aq2gf.us-east-1.elasticbeanstalk.com/
  region: "us-east-1"
  app: multi-docker
  env: "MultiDocker-env"
  # AWS S3 bucket
  bucket_name: "elasticbeanstalk-us-east-1-154382311469"
  # First time deployment exactly as app name
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
