sudo: required
services:
  - docker

before_install:
  - docker build -t emilerode/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - travis_wait docker run emilerode/react-test npm test -- --coverage

after_success:
  - docker build -t emilerode/multi-client ./client
  - docker build -t emilerode/multi-nginx ./nginx
  - docker build -t emilerode/multi-server ./server
  - docker build -t emilerode/multi-worker ./worker
 # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub    
  - docker push -t emilerode/multi-client
  - docker push -t emilerode/multi-nginx
  - docker push -t emilerode/multi-server
  - docker push -t emilerode/multi-worker
